# Generated by Django 4.1.3 on 2023-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_amenity_options_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="kind",
            field=models.CharField(
                choices=[
                    ("entire_place", "Entire Place"),
                    ("private_room", "Private Room"),
                    ("shared_room", "Shared Room"),
                ],
                max_length=20,
            ),
        ),
    ]
