# Generated by Django 4.1.3 on 2023-01-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0003_alter_experience_category_alter_experience_host_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start",
            field=models.TimeField(),
        ),
    ]
