# Generated by Django 4.1.3 on 2023-02-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0004_alter_experience_end_alter_experience_start"),
        ("medias", "0004_alter_video_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="experience",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="experiences.experience",
            ),
        ),
    ]
